# Generated by Django 2.1.7 on 2019-04-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_usage', models.IntegerField(default=0)),
                ('total_time', models.BigIntegerField(default=0)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine_type')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_usage', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machines.Machine')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machines.Machine_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
