# Generated by Django 2.1.7 on 2019-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usages', '0002_dailyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
