# Generated by Django 2.1.7 on 2019-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_unregistered_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregistered_card',
            name='tap_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
